version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbempleados
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: rootpassword
    networks:
      - stack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: employee-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - stack
  
networks:
  stack:
    name: stack
    driver: bridge
