FROM maven:3.9-amazoncorretto-17 AS builder
COPY pom.xml .
RUN mvn dependency:resolve -B
COPY src ./src
RUN mvn -DskipTests package

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=builder target/employee-0.0.1-SNAPSHOT.jar /app/employee.jar

ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASS=${DB_PASS}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "employee.jar"]
