services:
  employee-api:
    container_name: employee-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/root/data/h2  # Para persistencia de datos H2 embebida
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped

volumes:
  h2-data:
