logging:
  level:
    org.springframework: DEBUG  # Enables debug logging for Spring Boot
    org.hibernate: DEBUG         # Enables debug logging for Hibernate (if using JPA)
    # You can add other packages you want to debug as well

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bdempleados?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  application:
    name: employee-api

server:
  port: 8080
    